### ISSUE TITLE
Feature request: FAB outside bottom bar

### ISSUE THREAD

**Issue by eivihnd** [Frezyx/bottom_bar_with_sheet#12]
Amazing work on the bottom_bar_with_sheet!

Would it be possible to add a fourth option to the placement of the FAB, in order to place the FAB outside the bottom bar?
This would allow for hiding the bottom bar completely (height 0), and the bottom bar could be opened by clicking the FAB.

**Inspiration:** 
This piece by Eike Drescher, [UpLabs](https://www.uplabs.com/posts/slide-up-menu)

![image](https://user-images.githubusercontent.com/69076939/95653512-8043e600-0af9-11eb-9b13-ddc11be2892f.png)

**Comment by Frezyx** [comment]
Hello @eivihnd ✋ 
Thank you so much for your suggestion to improve the package 😃 
I will try to find a way to make this feature.

You can also commit to this repository if you have an example solution.
The package is open for changes 👐

**Comment by eivihnd** [comment]
Thank you for the feedback! :) 
I do not have an example solution yet, and I am fairly new to Flutter, but if I can come up with something, I will share it with you.

**Comment by Frezyx** [comment]
Hello @eivihnd ! ✋
I created a new functionality in this [pull request](https://github.com/Frezyx/bottom_bar_with_sheet/pull/14)

**Comment by Frezyx** [comment]
Now you can use [this example](https://github.com/Frezyx/bottom_bar_with_sheet/blob/master/example/lib/examples/fab_outside_bottom_bar.dart) to create UI that you offered.

**Comment by Frezyx** [comment]
Here is preview of this [example](https://github.com/Frezyx/bottom_bar_with_sheet/blob/master/example/lib/examples/fab_outside_bottom_bar.dart)

<img width="300" src="https://user-images.githubusercontent.com/40857927/97244521-00f92680-180a-11eb-94d4-003b1fb71e8a.gif">

**Comment by eivihnd** [comment]
Amazing work, Frezyx!
It looks really good. I will test it out.

On the topic of non-standard way to use the button and sheet:
From a usability standpoint, do you think this can be used as the main menu?
I think it is an interesting approach, as the menu button is placed closer to your natural position of your fingers, as opposed to the (iOS) standard top left. With large screens one must stretch to reach the top, but with this it is much more easy to reach.

Some would argue that it is not good practice to hide the menu, however that is what we normally do with the hamburger menu. Furthermore, if the app is designed in a way where you normally do not need to use the menu, I think this is a very interesting approach. 

Again, thank you so much!

(Btw, if I need (paid) Flutter development work done in the future, can I contact you?)

**Comment by Frezyx** [comment]
@eivihnd , I'm glad if solved your problem 😃 

It will be very cool if you can give a star to this repository ⭐ 
This helps to promote the project 📊 

Ready to help you with your questions.
You can send me an email at 📫 youngfrezyx@gmail.com
