### ISSUE TITLE
Sheet Closed when clicking Textfield 

### ISSUE THREAD

**Issue by Subash22** [Frezyx/bottom_bar_with_sheet#16]
Bottom Sheet closes automatically when clicking text field inside sheet or while filling the form...

**Comment by Frezyx** [comment]
Hello @Subash22 ✋ 

Does this only happen with the text form?
Other active elements don't reset the state ?

**Comment by Frezyx** [comment]
This issue was fixed in this https://github.com/Frezyx/bottom_bar_with_sheet/pull/29 pr
