### ISSUE TITLE
BottomBarWithSheetItem splash issues

### ISSUE THREAD

**Issue by jlnrrg** [Frezyx/bottom_bar_with_sheet#37]
I noticed that the build of BottomBarWithSheetItem leads to a few inconveniences.
1. the icon on select pushes the label down. I think this is because the splash in nonexistent beforehand.

2. The area that excepts input is way to small. For the bottom bar I would expect the touchable area to fill the whole the whole Column/Row. 

@Frezyx I would be happy to assist you also in this project, but please add a few more comments beforehand :see_no_evil: 

https://user-images.githubusercontent.com/77293597/115225377-4a1d9980-a10e-11eb-9fb2-981de7e62f17.mp4

**Comment by Frezyx** [comment]
Hello @jlnrrg ✋🏻 
Glad to see you again 😄 

Indents appear due to the fact that earlier the widget was adapted for icons - circles.
Now I am moving away from the old concept. If you can do it so as not to hurt the functionality, it will be great

**Comment by Frezyx** [comment]
This functionality is fixed by (2.0.0)[https://github.com/Frezyx/bottom_bar_with_sheet/releases/tag/2.0.0] version release
