### ISSUE TITLE
Divider between Appbar and Content

### ISSUE THREAD

**Issue by jlnrrg** [Frezyx/bottom_bar_with_sheet#38]
Rn the content is hard to visually seperate when the background color for the AppBar and the content is both white.
The addition of a Divider() between them might come in useful here.

![image](https://user-images.githubusercontent.com/77293597/115225769-c44e1e00-a10e-11eb-90df-ffcc66dc3c85.png)

**Comment by Frezyx** [comment]
In this case you can create Divider on top of your **sheetChild**
I will not mind if you think of a custom field for this.
