### ISSUE TITLE
Overwork of mandatory elements

### ISSUE THREAD

**Issue by jlnrrg** [Frezyx/bottom_bar_with_sheet#39]
Right now these parameters are mandatory in BottomBarWithSheet:
- bottomBarTheme
- sheetChild
- onSelectItem
and also the MainActionButtonTheme requires an icon.

From my point of view the MainActionButtonTheme (and MainActionButton) should orientate more on the FloatingActionButton which has no required field. If there is no icon provided this does not matter, as the FAB is there but just without an icon.
Also the bottomBarTheme must not be required as the package should provide default settings based on the Theme.of(context) values or internal default values.

**Comment by Frezyx** [comment]
I completely agree with you !
I realized this very late and now I'm trying to figure out how to fix it as imperceptibly as possible.
