### ISSUE TITLE
Close Sheet onTap outside

### ISSUE THREAD

**Issue by jlnrrg** [Frezyx/bottom_bar_with_sheet#40]
Basically the title.
When the user touches something outside the expanded BottomBar, the bar should collapse again.

**Comment by Frezyx** [comment]
In this I believe that it should be possible to customize this.
Since the functionality of the modal window is not always needed.

**Comment by Frezyx** [comment]
Hello @jlnrrg ✋🏻 
Hello @fhidal01 !
I release new [2.0.0](https://github.com/Frezyx/bottom_bar_with_sheet/releases/tag/2.0.0) version of package with ** BottomBarWithSheetController**
Now you can toggle BottomBarWithSheet state by this controller functionality.
___________________________
Sorry for the long wait 😅
