### ISSUE TITLE
Increase item touch area 

### ISSUE THREAD

**Issue by murilozas** [Frezyx/bottom_bar_with_sheet#48]
I noticed that the item gesture detector only runs after tapping inside the icon. Unlike default TabBar where there is an touchable area around.

In my usage experience, sometimes I have to tap again. I believe if increasing the touch area would solve this problem.

**Comment by Frezyx** [comment]
Hello @murilozas ✋🏻 
Thank you for this issue !
I agree. This needs to be changed

**Comment by Frezyx** [comment]
This 🐛bug is fixed in https://github.com/Frezyx/bottom_bar_with_sheet/pull/50 pr
You can test this functionality in 2.0.1 version
