### ISSUE TITLE
Doesn't fill the bottom of the app in iOS

### ISSUE THREAD

**Issue by yakeer** [Frezyx/bottom_bar_with_sheet#5]
![image](https://user-images.githubusercontent.com/19772782/94363079-74532f80-00c8-11eb-8a2b-924deeff0a36.png)

It's like only in the SafeView area...
would appreciate a fix in order to use it.

**Comment by Frezyx** [comment]
Hi! ✋ 
Thank you so much for pointing out this bug.
I will try to solve this problem in the near future.

**Comment by Frezyx** [comment]
Hello!
Now you can add this argument in **BottomBarTheme:**

```dart
contentPadding: EdgeInsets.only(bottom: 20),
```

<br>

And the result will be:
![Снимок экрана 2020-09-30 в 02 47 23](https://user-images.githubusercontent.com/40857927/94622761-729d8d80-02bb-11eb-98fc-afecdd71e741.png)

✔️ Solved here -> https://github.com/Frezyx/bottom_bar_with_sheet/pull/6

**Comment by yakeer** [comment]
Thanks.
