### ISSUE TITLE
Real life usage

### ISSUE THREAD

**Issue by adrianvintu** [Frezyx/bottom_bar_with_sheet#54]
The widget looks interesting. Are there some people who can provide real life examples where this is used? How does it help that the area is opened below navigation?

**Comment by Frezyx** [comment]
Hello @adrianvintu !
You can check Github search
![image](https://user-images.githubusercontent.com/40857927/151767527-c9b674c6-4843-4357-8f24-00406895ac7d.png)

**Comment by adrianvintu** [comment]
Is there any serious app there? I tested 4 pages of results and they seem to be practice code.

**Comment by deezaster** [comment]
define serious.
here is a screenshot of a club app

![IMG_0597](https://user-images.githubusercontent.com/1539838/151782817-8599e562-e188-4583-9e84-1b272c436f5e.png)

**Comment by adrianvintu** [comment]
@deezaster Not practice code. I thought it was pretty clear.

**Comment by Frezyx** [comment]
> 

I really hope that developers of serious applications making his repositories private
